# Generated by Django 6.0.1 on 2026-01-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='obs',
        ),
    ]
