# Generated by Django 6.0.1 on 2026-01-15 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_remove_genre_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
    ]
